apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmalert
  labels:
    app: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/manifests/vmalert
    repoURL: 'https://github.com/petrovkazanksvu/krukov'
    targetRevision: master
  project:  monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
